### PR TITLE
File logging

### PR DESCRIPTION
**Pull request by deldesir**
Add possibility to log to file.

### CODE REVIEW

**Comment by deldesir** [comment]
This PR is not necessary. Zimscraperlib does have file logging feature. To use it, add file="/output/run.log" in https://github.com/openzim/youtube/blob/0574bce2795bd816f6b8d9b5eb4b942dc198366e/youtube2zim/constants.py#L34.

**Comment by holta** [comment]
> This PR is not necessary. Zimscraperlib does have file logging feature. To use it, add file="/output/run.log" in https://github.com/openzim/youtube/blob/0574bce2795bd816f6b8d9b5eb4b942dc198366e/youtube2zim/constants.py#L34.

Awesome news that you got to the bottom of this!  cc: @georgejhunt

(Another vote for Clean Docs, so everyone avoids wasting time!)

Question: Is reverting some or all of this PR now appropriate?

**Comment by deldesir** [comment]
I think so. Simplicity is better.

**Comment by holta** [comment]
Great news if this is tremendously simplified going forward!

Maybe follow up on the ticket below?

- PR iiab/youtube#3

**Pull request merged**
